# .readthedocs.yaml
version: 2

sphinx:
  configuration: source/conf.py   # đường dẫn tới file conf.py

python:
  version: 3.10                  # phiên bản Python muốn dùng
  install:
    - requirements: requirements.txt
